### PR TITLE
Add patch for ARM64 macOS BTLS build.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot-mono-builds/issues/79

### CODE REVIEW

**Comment by bruvzg** [comment]
Also added https://github.com/mono/mono/pull/21597 as a patch, to fix build with new Xcode.

**Review by akien-mga — APPROVED** [review]
Amazing! Looks great, I'll give it a try asap.

**Review by akien-mga — APPROVED** [review]
Tested on the build server, it generated libmono-btls-shared.dylib fine for arm64!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
